cartinfo/urls.py
# python3
from django.conf.urls import url
from cartinfo import views
from django.views.generic import TemplateView

urlpatterns= [
    url('^$', views.cart_info,name='cart'),
    url('^addcart', views.add_cart),
    url('^deletecart', views.delete_cart),
    url('^cartcount', views.cart_count),
    url('^addorder', views.add_order),
    url('^orderlist', views.order_list,name='orderlist'),
    url('^placeorder', views.place_order,name='placeorder'),

]

friutday/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from memberapp import views
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^prolist/$', views.prolist_list, name='goodslist'),
    url(r'^detail/', views.deatil_one),
    url(r'^user/', include('userinfo.urls')),
    url(r'^cart/', include('cartinfo.urls')),
    
    url(r'^test/$', TemplateView.as_view(template_name="test.html"), name='test'),
]

cartinfo/models.py
# coding=utf-8

from django.db import models
from userinfo.models import UserInfo
from memberapp.models import Goods


ORDERSTATUS = (
        (1, "未支付",),
        (2, "已支付"),
        (3, "订单取消"),
    )


class CartInfo(models.Model):
    user = models.ForeignKey(UserInfo, db_column='user_id', on_delete=models.CASCADE)
    good = models.ForeignKey(Goods, db_column='good_id', on_delete=models.CASCADE)
    ccount = models.IntegerField('数量', db_column='cart_count')

    def __unicode__(self):
        return self.user

    def __str__(self):
        return self.ccount

    def get_absolute_url(self):
        return '???'

    class Meta():
        db_table = 'cartinfo'


class Order(models.Model):
    user = models.ForeignKey(UserInfo, db_column='user_id', on_delete=models.CASCADE)
    orderNo= models.CharField("订单号", max_length=200)
    ads= models.CharField("收件人", max_length=200)
    acot= models.CharField("总数", max_length=200)
    acounts= models.CharField("价格", max_length=200)
    cals = models.TextField("orderdetail", null=True, blank=True)
    orderStatus = models.IntegerField("订单状态", blank=True, choices=ORDERSTATUS, default='1')

    def __unicode__(self):
        return self.user

    def get_orderStatusDisplay(self):
        if self.orderStatus == 1:
            return u'未支付'
        elif self.orderStatus == 2:
            return u'已支付'
        elif self.orderStatus == 3:
            return u'订单取消'
        else:
            return u''

memberapp/models.py
# coding=UTF-8
from django.db import models
# python2.x
# from django.core.urlresolvers import reverse


# 商品类型


class GoodsType(models.Model):
    title = models.CharField('名称', max_length=30)
    desc = models.CharField('描述', max_length=200, default='商品描述')
    flag = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='static/image/good_type', default='normal.png')
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta():
        db_table = 'goods_Type'


# 商品字段
class Goods(models.Model):
    title = models.CharField('名称', max_length=50 )
    price = models.DecimalField('商品价格', max_digits=8, decimal_places=2)
    desc = models.CharField('描述', max_length=1000)
    # desc = models.CharField('描述', max_length=1000, default='商品的描述信息')
    picture = models.ImageField('商品照片', upload_to='static/images/goods',default='normal.png')
    isDelete = models.BooleanField(default=False)
    type = models.ForeignKey(GoodsType,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/detail/?good={}/'.format(self.id)

    class Meta():
        db_table = 'goods'

memberapp/views.py
#-*- coding: UTF-8 -*-
from django.shortcuts import render, get_object_or_404, redirect,HttpResponse
from django.http import request, response
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.exceptions import ObjectDoesNotExist
from django.db import DataError, DatabaseError
import logging
import random
from django.http import JsonResponse
import math
from .models import *
from cartinfo.models import CartInfo
# Create your views here.

# 共用分页逻辑
# 自己实现的分页逻辑(然而并没有什么卵用)
# 匹配当前页 index == (x for x in 总页数)
# def pange_index(goods, index):
#     index = int(index)
#     if int(index) <= 0:
#         index = 1
#     try:
#         goods_counts = goods.objects.count()
#         counts_index = math.ceil(goods_counts / 10)
#         if index >= counts_index:
#             index = counts_index
#             index_page = goods.objects.all()[(index - 1) * 10:]
#         else:
#             index_page = goods.objects.all()[(index - 1) * 10 : index * 10]
#     except DatabaseError as e:
#         logging.warning(e)
#     return index_page, counts_index


# 抽象出的通用的分页逻辑
def page_index(goods, index, Type):
    if not Type:
        contact_list = goods.objects.all()
    else:
        goods_type = get_object_or_404(GoodsType,title=Type)
        contact_list = goods_type.goods_set.all()
    # 目前来看的效果
    paginator = Paginator(contact_list, 10, 2)
    p_totalpage = paginator.page_range
    try:
        good_contact = paginator.page(index)
    except PageNotAnInteger:
        good_contact = paginator.page(1)
    except EmptyPage:
        good_contact = paginator.page(paginator.num_pages)

    return good_contact


# 首页的展示逻辑 待优化(ajax)
def index(request):
    try:
        good_fruit_type = get_object_or_404(GoodsType, title='新鲜水果')
        fruit_goods = random.sample(list(good_fruit_type.goods_set.all()), 4)
        good_fruit_meet = get_object_or_404(GoodsType, title='精品肉类')
        meet_goods = random.sample(list(good_fruit_meet.goods_set.all()), 4)
        good_fruit_water = get_object_or_404(GoodsType, title='海鲜水产')
        water_goods = random.sample(list(good_fruit_water.goods_set.all()), 4)
        vagetables_good_type = get_object_or_404(GoodsType, title='新鲜蔬菜')
        vegetables_good = random.sample(list(vagetables_good_type.goods_set.all()), 4)
        quick_snacks_good = get_object_or_404(GoodsType, title='速冻食品')
        quick_food = random.sample(list(quick_snacks_good.goods_set.all()), 4)
        egg_goods_type = get_object_or_404(GoodsType, title='禽类蛋品')
        eggs_foods = random.sample(list(egg_goods_type.goods_set.all()), 4)
        #content = {'fruit_goods': fruit_goods, 'meet_goods': meet_goods, 'water_goods': water_goods, 'vegetables_good': vegetables_good, 'quick_food':quick_food, 'eggs_foods':eggs_foods}
    except DatabaseError as e:
        logging.warning(e)

    user_id = request.session.get('user_id')
    if user_id:
        mycartc = CartInfo.objects.filter(user=user_id).count()
        cart_foods = {'mycartc': mycartc}
    return render(request, 'index.html', {'good_list': locals()})


# 商品列表页的展示逻辑(代码的复用性)
def prolist_list(request, Type=None):
    idv = request.GET.get('page')
    if request.GET.get('Type'):
        Type = request.GET.get('Type')[:-1]
    try:
        goods_list = page_index(Goods, idv, Type)
        hot_goods = random.sample(list(Goods.objects.all()), 2)
    #    page_content = {'goods_list': goods_list, 'hot_goods' : hot_goods}
        # 页面上现实的上一页和下一页是被urlEncode转码的
    except DatabaseError as e:
        logging.warning(e)

    return render(request, 'list.html', {'content': locals()})


# show the good's detail
def deatil_one(request):
    good_id = request.GET.get('good')[:-1]
    try:
        good = Goods.objects.get(id=good_id)
        good_type = good.type
        hot_good = good_type.goods_set.order_by('-id').all()[:2]
        # Typefood = GoodsType.objects.order_by(id='id')
    except ObjectDoesNotExist as e:
        logging.warning(e)
    if request.COOKIES.get('Recently_Viewed'):
        cookie_good = request.COOKIES.get('Recently_Viewed')
        list_good = cookie_good.split(',')
        if good.id in list_good:
            list_good.remove(good.id)
        # 如果最近浏览多的话那么将最久没有被浏览的那个商品删除
        if len(list_good) >= 5:
            list_good.pop()
        list_good = [good_id] + list_good
        cookie_good_new = ','.join(list_good)
    else:
        cookie_good_new = good_id
    user_id = request.session.get('user_id')
    mycartc = 0
    if user_id:
        mycartc = CartInfo.objects.filter(user=user_id).count()

    # cookie处理数据添加的位置
    response = render(request, 'detail.html', {'goodone': good, 'hot_list': hot_good, 'mycartc':mycartc})
    response.set_cookie('Recently_Viewed', cookie_good_new, max_age=3000)
    return response

memberapp/templates/cart.html
{% extends 'index.html' %}
{% block title %}天天果园-购物车{% endblock %}
{% block content %}
    {% load staticfiles %}
	<div class="search_bar clearfix">
		<a href="{% url 'index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>{{mycartc}}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for find_good in find_goods %}
        <ul class="cart_list_td clearfix">
            <li class="col01"><input type="checkbox" name="check" onclick="count()"></li>
            <li class="col02"><img src="/{{ find_good.good.picture }}"></li>
            <li class="col03">{{ find_good.good.title }}
				<!--<br><em>{{ find_good.good.price }}/500g</em>-->
			</li>
            <li class="col04">500g</li>
            <li class="col05">{{ find_good.good.price }}</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl">+</a>
                    <input type="text" class="num_show fl" value="{{ find_good.ccount }}">
                    <a href="javascript:;" class="minus fl">-</a>
                </div>
            </li>
            <li class="col07">{% widthratio find_good.good.price  1 find_good.ccount %}  元</li>
            <li class="col08"><a  onclick="deletea({{find_good.id}})"  style="cursor: pointer;">删除</a></li>
	    </ul>
    {% endfor %}


	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="allcheck" id="allcheck"/></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="acounts">0</em><br>共计<b id="acot">0</b>件商品</li>
		<li class="col04"><a onclick="caToor()">去结算</a></li>
	</ul>
{% endblock %}
{% block script %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
	$('#allcheck').click(function(){
		if(this.checked){
			$('input[name="check"]').prop('checked',true);
			var s= $('input[name="check"]:checked').length;
			$('#acot').text(s);
		}else{
       		$('input[name="check"]').prop('checked',false);
			var s= $('input[name="check"]:checked').length;
			$('#acot').text(s);
		}
		var a=0;
		$.each($('input:checkbox:checked').parent().nextAll('.col07'),function(){
		a=a+parseInt(this.innerText.replace(/[^0-9]+/g, ''))

        });
		$('#acounts').text(a);

    });
	function count(){
		var s= $('input[name="check"]:checked').length;
		$('#acot').text(s);
		var a=0;
		$.each($('input:checkbox:checked').parent().nextAll('.col07'),function(){
			a=a+parseInt(this.innerText.replace(/[^0-9]+/g, ''))
        });
		$('#acounts').text(a);
	}
	function deletea(cart_id){
		$.ajax({
                url: '/cart/deletecart',
                type: 'get',
                datatype: 'json',
                data:{
                	'cart_id':cart_id,
                },
                success:function (data) {
                    location.href  ="{% url 'cart' %}";
                },
                error:function (error) {
                	console.log(error);
                    alert('添加失败, 请检查网络并重新添加. 失败原因见' + error)
                }
        })
	}


	function caToor(){
		var cals=[];
		<!--double each can push all {} into []-->
		$.each($('input:checkbox:checked').parent(),function(){
			var cal={};
			$.each($(this).nextAll(),function(){
				if(this.className=='col02'){
					cal['img']=$(this).children("img")[0].src;
				}
				if(this.className=='col03'){
					cal['title']=this.innerText;
				}
				if(this.className=='col04'){
					cal['wi']=this.innerText;
				}
				if(this.className=='col05'){
					cal['price']=this.innerText;
				}
				if(this.className=='col06'){
					cal['ac']=$(this).find('input')[0].defaultValue;
				}
				if(this.className=='col07'){
					cal['count']=this.innerText;
				}

			});
			cals.push(cal);
		});
		console.log(cals);
		sessionStorage.setItem('cals',JSON.stringify(cals));
		sessionStorage.setItem('acounts',$('#acounts').text());
		sessionStorage.setItem('acot',$('#acot').text());
		location.href = 'placeorder';
	}

	</script>
{% endblock %}

memberapp/templates/detail.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block title %}天天果园-商品详情{% endblock %}
{% block content %}
	<div class="search_bar clearfix">
		<a href="{% url 'index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{mycartc}}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="/prolist/?page=1&Type=新鲜水果/" class="fruit">新鲜水果</a></li>
					<li><a href="/prolist/?page=1&Type=海鲜水产/" class="seafood">海鲜水产</a></li>
					<li><a href="/prolist/?page=1&Type=精品肉类/" class="meet">精品肉类</a></li>
					<li><a href="/prolist/?page=1&Type=禽类蛋品/" class="egg">禽类蛋品</a></li>
					<li><a href="/prolist/?page=1&Type=新鲜蔬菜/" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/prolist/?page=1&Type=速冻食品/" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/{{ goodone.picture }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goodone.title }}</h3>
			<p>草莓浆果柔软多汁，味美爽口，适合速冻保鲜贮藏。草莓速冻后，可以保持原有的色、香、味，既便于贮藏，又便于外销。</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goodone.price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:add();" class="add fr">+</a>
					<a href="javascript:sub();" class="minus fr">-</a>
				</div> 
			</div>
			<div class="total" id="total_">总价：<em></em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a  class="add_cart" id="add_cart" style="cursor: pointer;">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for hotfood in hot_list %}
                        <li>
                            <a href="{{ hotfood.get_absolute_url }}"><img src="/{{ hotfood.picture }}"></a>
                            <h4><a href="{{ hotfood.get_absolute_url }}">{{ hotfood.title }}</a></h4>
                            <div class="prize">{{ hotfood.price }}</div>
                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}
{% block script %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

        $(function () {

            var count = $('.num_show').val();
            var total = count * $('.show_pirze em').text();
            $('#total_ em').text(total.toFixed(2));



        });
        function add() {
            var numa = parseInt($('.num_show').val());
            $('.num_show').val(numa+1);
            $('.num_show').removeAttr("disabled");
            $('.num_show').blur();
            total()
        }
        function sub() {
            var numa = parseInt($('.num_show').val());
            if (numa > 1){
                $('.num_show').val(numa-1);
            }else {
                $('.num_show').attr('disabled', 'disabled');
            }
            $('.num_show').blur();
            total();
        }
        function total() {
            var count = $('.num_show').val();
            var total = count * $('.show_pirze em').text();
            $('#total_ em').text(total.toFixed(2));
        }
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});
			});
			$.ajax({
                url: '/cart/addcart/?good_id='+ '{{ goodone.id }}'+ '&gcount='+ $('.num_show').val(),
                type: 'get',
                datatype: 'json',
                success:function (data) {
					console.log(typeof($('.num_show').val()));
					console.log(typeof($('#show_count').text()));

                    $('#show_count').text(parseInt($('.num_show').val()) + parseInt($('#show_count').text()));
                },
                error:function (error) {
                	console.log(error);
                    alert('添加失败, 请检查网络并重新添加. 失败原因见' + error)
                }
            })
		})

	</script>
{% endblock %}

memberapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天果园-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'index' %}" class="login_logo"><img src="{% static 'images/logo02.jpeg' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{%url 'register'%}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'login_in' %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ user_info.uname }}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name=""/>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
                        <div><p>{{ message_error }}</p></div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>版权所有 ©2017上海天天鲜果电子商务有限公司  保留所有权利 | 沪ICP备12042163</p>
		<p>天天果园  鲜果网购</p>
	</div>
	
</body>
</html>

memberapp/templates/skin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

memberapp/templates/test.html
{% extends 'index.html' %}
{% block title %}天天果园-购物车{% endblock %}
{% block content %}
    {% load staticfiles %}

	<a  onclick="test()"  style="cursor: pointer;">删除</a>



{% endblock %}
{% block script %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">

	function test(){
		$.ajax({
                url: '/pay/test',
                type: 'get',
                datatype: 'json',
                data:{

                },
                success:function (data) {
                   	console.log('ok')
                },
                error:function (error) {
                	console.log(error);

                }
        })
	}



	</script>
{% endblock %}

memberapp/templates/user_center_order.html
{#<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">#}
{#<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">#}
{#<head>#}
{#	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">#}
{#	<title>天天果园-用户中心</title>#}
{#	<link rel="stylesheet" type="text/css" href="css/reset.css">#}
{#	<link rel="stylesheet" type="text/css" href="css/main.css">#}
{#</head>#}
{#<body>#}
{#	<div class="header_con">#}
{#		<div class="header">#}
{#			<div class="welcome fl">欢迎来到天天果园!</div>#}
{#			<div class="fr">#}
{#				<div class="login_info fl">#}
{#					欢迎您：<em>睡了个觉</em>#}
{#				</div>#}
{#				<div class="login_btn fl">#}
{#					<a href="login.html">登录</a>#}
{#					<span>|</span>#}
{#					<a href="register.html">注册</a>#}
{#				</div>#}
{#				<div class="user_link fl">#}
{#					<span>|</span>#}
{#					<a href="user_center_info.html">用户中心</a>#}
{#					<span>|</span>#}
{#					<a href="cart.html">我的购物车</a>#}
{#					<span>|</span>#}
{#					<a href="user_center_order.html">我的订单</a>#}
{#				</div>#}
{#			</div>#}
{#		</div>		#}
{#	</div>#}
{% extends 'index.html' %}
{% block title %}天天果园-用户中心{% endblock %}
{% block content %}
    {% load staticfiles %}
	<div class="search_bar clearfix">
		<a href="{% url 'index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'orderlist' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'useraddress' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

				{% for order in orders %}
					<ul class="order_list_th w978 clearfix">
						<li class="col01">2016-8-21 17:36:24</li>
						<li class="col02">订单号：{{ order.orderNo }}</li>
						<li class="col02 stress">{{ order.get_orderStatus_display }}</li>
					</ul>
					<table class="order_list_table w980">
						<tbody>
							<tr>
								<td width="55%">
									{%for a in order.cals%}


									<ul class="order_goods_list clearfix">
										<li class="col01"><img src="{{a.img}}"></li>
										<li class="col02">{{a.title}}<em>{{a.price}}/{{a.wi}}</em></li>
										<li class="col03"></li>
										<li class="col04">{{a.count}}</li>
									</ul>
									{% endfor %}
								</td>
								<td width="15%">{{ order.acounts }}元</td>
								<td width="15%">{{ order.ads }}</td>
								<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							</tr>
						</tbody>
					</table>

				{% endfor %}


				<div class="pagenation">
					<a href="#">上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>

{% endblock %}

{#	<div class="footer">#}
{#		<div class="foot_link">#}
{#			<a href="#">关于我们</a>#}
{#			<span>|</span>#}
{#			<a href="#">联系我们</a>#}
{#			<span>|</span>#}
{#			<a href="#">招聘人才</a>#}
{#			<span>|</span>#}
{#			<a href="#">友情链接</a>		#}
{#		</div>#}
{#		<p>版权所有 ©2017上海天天鲜果电子商务有限公司  保留所有权利 | 沪ICP备12042163</p>#}
{#		<p>天天果园  鲜果网购</p>#}
{#	</div>#}
{#	#}
{#</body>#}
{#</html>#}